=== Robin-Ln/M2_Langage_UE_Conception_Objet/XMLs/Programme.dtd
<!ELEMENT Programme (IntegerExpression 
					| DoubleExpression
					| StringExpression
					| BooleanExpression
					| UnResolveSymbole
					| MultiplicationExpression 
					| AdditionExpression
					| InferieurExpression
					| Declaration
					| Affectation
					| ProcedureCall
					| If
					| Block)*>
<!ATTLIST Programme 
	valide CDATA #IMPLIED
>

<!ELEMENT IntegerExpression EMPTY>
<!ATTLIST IntegerExpression 
	id ID #REQUIRED
	valeur CDATA #REQUIRED
>

<!ELEMENT BooleanExpression EMPTY>
<!ATTLIST BooleanExpression 
	id ID #REQUIRED
	valeur CDATA #REQUIRED
>

<!ELEMENT DoubleExpression EMPTY>
<!ATTLIST DoubleExpression 
	id ID #REQUIRED
	valeur CDATA #REQUIRED
>

<!ELEMENT StringExpression EMPTY>
<!ATTLIST StringExpression 
	id ID #REQUIRED
	valeur CDATA #REQUIRED
>

<!ELEMENT UnResolveSymbole EMPTY>
<!ATTLIST UnResolveSymbole 
	id ID #REQUIRED
	nomSymbole CDATA #REQUIRED
>

<!ELEMENT MultiplicationExpression EMPTY>
<!ATTLIST MultiplicationExpression 
	id ID #REQUIRED
	idOperandeGauche IDREF #REQUIRED
	idOperandeDroite IDREF #REQUIRED
>

<!ELEMENT AdditionExpression EMPTY>
<!ATTLIST AdditionExpression 
	id ID #REQUIRED
	idOperandeGauche IDREF #REQUIRED
	idOperandeDroite IDREF #REQUIRED
>

<!ELEMENT InferieurExpression EMPTY>
<!ATTLIST InferieurExpression 
	id ID #REQUIRED
	idOperandeGauche IDREF #REQUIRED
	idOperandeDroite IDREF #REQUIRED
>

<!ELEMENT Declaration EMPTY>
<!ATTLIST Declaration 
	nomSymbole CDATA #REQUIRED
>

<!ELEMENT Affectation EMPTY>
<!ATTLIST Affectation 
	nomSymbole CDATA #REQUIRED
	idExpression IDREF #REQUIRED
>

<!ELEMENT ProcedureCall EMPTY>
<!ATTLIST ProcedureCall 
	nomProcedure CDATA #REQUIRED
	idExpressions IDREFS #REQUIRED
>

<!ELEMENT If EMPTY>
<!ATTLIST If 
	idExpression IDREF #REQUIRED
	idBlockTrue IDREF #REQUIRED
	idBlockFalse IDREF #IMPLIED
>


<!ELEMENT Block (IntegerExpression 
				| DoubleExpression
				| StringExpression
				| BooleanExpression
				| UnResolveSymbole
				| MultiplicationExpression 
				| AdditionExpression
				| InferieurExpression
				| Declaration
				| Affectation
				| ProcedureCall
				| If
				| Block)*>
<!ATTLIST Block 
	id ID #REQUIRED
>

=== Robin-Ln/M2_Langage_UE_Conception_Objet/XMLs/ProgrammeNonValide.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE Programme SYSTEM "Programme.dtd">


<Programme>

	<IntegerExpression id="id0" valeur="10" />

	<IntegerExpression id="id1" valeur="2" />

	<DoubleExpression id="id3" valeur="2.0" />

	<StringExpression id="id5" valeur="2.0" />

	<UnResolveSymbole id="id7" nomSymbole="y" />

	<MultiplicationExpression id="id2"
		idOperandeGauche="id0" idOperandeDroite="id1" />

	<MultiplicationExpression id="id4"
		idOperandeGauche="id0" idOperandeDroite="id3" />

	<MultiplicationExpression id="id6"
		idOperandeGauche="id0" idOperandeDroite="id5" />

	<MultiplicationExpression id="id8"
		idOperandeGauche="id0" idOperandeDroite="id7" />

	<MultiplicationExpression id="id11"
		idOperandeGauche="id0" idOperandeDroite="id7" />

	<Declaration nomSymbole="x" />

	<Declaration nomSymbole="x" />

	<Declaration nomSymbole="z" />

	<UnResolveSymbole id="id10" nomSymbole="z" />

	<MultiplicationExpression id="id9"
		idOperandeGauche="id10" idOperandeDroite="id7" />

	<Affectation nomSymbole="x" idExpression="id2" />

	<Affectation nomSymbole="x" idExpression="id4" />

	<Affectation nomSymbole="x" idExpression="id6" />

	<Affectation nomSymbole="x" idExpression="id8" />

	<Affectation nomSymbole="y" idExpression="id1" />

	<Affectation nomSymbole="x" idExpression="id9" />

	<Affectation nomSymbole="x" idExpression="id11" />

	<UnResolveSymbole id="id12" nomSymbole="l" />

	<Affectation nomSymbole="x" idExpression="id12" />

	<ProcedureCall idExpressions="id6" nomProcedure="print3" />


</Programme>

<!-- 
 var x;
 var x;
 var z;
 x = (10*2); 
 x = (10*2.0); 
 x = (10*"2.0"); 
 x = (10*y); 
 y = 2;
 x = (z*y); 
 x = (10*y); 
 print3(...)
-->

=== Robin-Ln/M2_Langage_UE_Conception_Objet/XMLs/ProgrammeValide.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE Programme SYSTEM "Programme.dtd">


<Programme>

	<IntegerExpression id="id0" valeur="10" />

	<IntegerExpression id="id1" valeur="2" />

	<MultiplicationExpression id="id2"
		idOperandeGauche="id0" idOperandeDroite="id1" />

	<InferieurExpression id="id5"
		idOperandeGauche="id1" idOperandeDroite="id0" />

	<Declaration nomSymbole="x" />

	<Declaration nomSymbole="z" />

	<Declaration nomSymbole="y" />

	<Affectation nomSymbole="x" idExpression="id2" />

	<Affectation nomSymbole="y" idExpression="id5" />

	<UnResolveSymbole nomSymbole="x" id="id4" />

	<AdditionExpression idOperandeDroite="id0"
		idOperandeGauche="id4" id="id3" />

	<Affectation nomSymbole="z" idExpression="id3" />

	<UnResolveSymbole nomSymbole="z" id="id6" />
	<UnResolveSymbole nomSymbole="y" id="id7" />

	<ProcedureCall idExpressions="id4" nomProcedure="print" />
	<ProcedureCall idExpressions="id6" nomProcedure="print" />
	<ProcedureCall idExpressions="id7" nomProcedure="print" />

	<Block id="id8">
		<ProcedureCall idExpressions="id4" nomProcedure="print" />
	</Block>
	<Block id="id9">
		<ProcedureCall idExpressions="id7" nomProcedure="print" />
	</Block>
	<If idExpression="id7" idBlockTrue="id8" idBlockFalse="id9" />

	<IntegerExpression id="id10" valeur="0" />
	<IntegerExpression id="id11" valeur="1" />
	<IntegerExpression id="id16" valeur="10" />
	<InferieurExpression id="id18"
		idOperandeGauche="id15" idOperandeDroite="id16" />
	<Declaration nomSymbole="cpt" />
	<Affectation nomSymbole="cpt" idExpression="id10" />
	
	<While idBlock="id14" idExpression="id18" />
	<Block id="id14">
		<Affectation nomSymbole="cpt" idExpression="id12" />
		<UnResolveSymbole nomSymbole="cpt" id="id15" />
		<AdditionExpression id="id12"
			idOperandeGauche="id15" idOperandeDroite="id11" />
		<ProcedureCall idExpressions="id15" nomProcedure="print" />
	</Block>
</Programme>

<!--
var x;
var z;
var y;
var cpt;
x = (10*2);
y = (2<10);
z = (x+10);
print(x);
print(z);
print(y);
if (y ){
   print(x);
}else{
   print(y);
}
cpt = 0;
while ((cpt<10) ){
   cpt = (cpt+1);
   print(cpt);
}
 -->
